### ISSUE TITLE
Since we use `appendWriteSync` perceived speed of transformation strategies has gone down a lot

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#248]
- It now takes roughly 10 minutes just to transform 1M block logs in call-block-logs-transformation
- It's been a while since I had run it, but I always thought it was faster
- A possible async solution could be to pipe all of transformer.onLine's `write` results in to a nodejs `WriteStream`

// cc @il3ven because you were interested in this last time

**Comment by il3ven** [comment]
I'd like to work on this issue. I will first check if `WriteStream` works and if it doesn't I will implement a queue.

**Comment by il3ven** [comment]
I want to confirm. I am a little confused. Should I work on this or the embedded database? Because if we go with a database we won't need this. I think for now we should fix this and later pick up the embedded database task.

**Comment by il3ven** [comment]
Implementing a queue is tempting and the engineer in me wants to do it but I don't want to implement something just because it's cool. I will work on the more important neume-network/data issues. Can you point me to an issue I can pick?

**Comment by TimDaub** [comment]
this one is good:

https://github.com/neume-network/strategies/issues/251

imagine we crawled a blocklogs crawl but no useful nft ids where in there and so all resulting extractor and transformation files wouldn't exist. It should still not throw errors on Github action

**Comment by il3ven** [comment]
If we ever decide to resolve this issue we can use [`WriteStream`](https://nodejs.org/api/stream.html#writablewritechunk-encoding-callback). It implements a buffer system so we won't have to implement a queue. As the buffer gets filled the application starts using more and more memory and garbage collection takes a hit. A quick fix is to increase the memory size for the application using `--max-old-space-size`.
